#include <iostream>
using namespace std;

// Прототипы функций
void calculateRemainder();
void calculateQuotient();

int main() {
    int choice;
    
    do {
        // Вывод меню
        cout << "Меню:" << endl;
        cout << "1. Найти остаток от деления разности чисел А и В на число С" << endl;
        cout << "2. Найти целую часть от деления числа А на сумму чисел В и С" << endl;
        cout << "0. Выход" << endl;
        cout << "Выберите пункт меню: ";
        cin >> choice;
        
        switch (choice) {
            case 1:
                calculateRemainder();
                break;
            case 2:
                calculateQuotient();
                break;
            case 0:
                cout << "Выход из программы." << endl;
                break;
            default:
                cout << "Неверный выбор. Попробуйте снова." << endl;
        }
    } while (choice != 0);
    
    return 0;
}

// Функция для вычисления остатка от деления разности А и В на С
void calculateRemainder() {
    // Тело функции будет реализовано позже
}

// Функция для вычисления целой части от деления А на сумму В и С
void calculateQuotient() {
    2
}
E21][D213JNDIP`2HFYU9E2PF2
F\824F
24F
24F\24
F
4\24FE132E132E23E32E32E



E23E32E32E2]